2022-03-23 17:28:14,804 INFO    MainThread:33988 [wandb_setup.py:_flush():75] Loading settings from C:\Users\theo-\.config\wandb\settings
2022-03-23 17:28:14,804 INFO    MainThread:33988 [wandb_setup.py:_flush():75] Loading settings from D:\Logiciel_école\GitHub\AIBSIF\src\model\wandb\settings
2022-03-23 17:28:14,804 INFO    MainThread:33988 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-23 17:28:14,804 INFO    MainThread:33988 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-23 17:28:14,804 INFO    MainThread:33988 [wandb_init.py:_log_setup():405] Logging user logs to D:\Logiciel_école\GitHub\AIBSIF\src\model\wandb\run-20220323_172814-1olf1kr5\logs\debug.log
2022-03-23 17:28:14,805 INFO    MainThread:33988 [wandb_init.py:_log_setup():406] Logging internal logs to D:\Logiciel_école\GitHub\AIBSIF\src\model\wandb\run-20220323_172814-1olf1kr5\logs\debug-internal.log
2022-03-23 17:28:14,805 INFO    MainThread:33988 [wandb_init.py:_jupyter_setup():355] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000028FBC2D58E0>
2022-03-23 17:28:14,805 INFO    MainThread:33988 [wandb_init.py:init():439] calling init triggers
2022-03-23 17:28:14,805 INFO    MainThread:33988 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-03-23 17:28:14,805 INFO    MainThread:33988 [wandb_init.py:init():492] starting backend
2022-03-23 17:28:14,805 INFO    MainThread:33988 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn, using: spawn
2022-03-23 17:28:14,848 INFO    MainThread:33988 [backend.py:ensure_launched():219] starting backend process...
2022-03-23 17:28:17,854 INFO    MainThread:33988 [backend.py:ensure_launched():224] started backend process with pid: 22852
2022-03-23 17:28:17,855 INFO    MainThread:33988 [wandb_init.py:init():501] backend started and connected
2022-03-23 17:28:18,207 INFO    MainThread:33988 [wandb_run.py:_label_probe_notebook():947] probe notebook
2022-03-23 17:28:18,208 INFO    MainThread:33988 [wandb_run.py:_label_probe_notebook():957] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-03-23 17:28:18,208 INFO    MainThread:33988 [wandb_init.py:init():565] updated telemetry
2022-03-23 17:28:19,014 INFO    MainThread:33988 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-23 17:28:49,021 INFO    MainThread:33988 [interface_shared.py:_communicate_run():322] couldn't get run from backend
2022-03-23 17:28:49,021 ERROR   MainThread:33988 [wandb_init.py:init():601] backend process timed out
2022-03-23 17:28:49,021 ERROR   MainThread:33988 [wandb_init.py:init():610] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-03-23 17:28:49,059 ERROR   MainThread:33988 [wandb_init.py:init():981] error
Traceback (most recent call last):
  File "d:\python\lib\site-packages\wandb\sdk\wandb_init.py", line 954, in init
    run = wi.init()
  File "d:\python\lib\site-packages\wandb\sdk\wandb_init.py", line 614, in init
    backend.cleanup()
  File "d:\python\lib\site-packages\wandb\sdk\backend\backend.py", line 248, in cleanup
    self.interface.join()
  File "d:\python\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 467, in join
    super().join()
  File "d:\python\lib\site-packages\wandb\sdk\interface\interface.py", line 630, in join
    _ = self._communicate_shutdown()
  File "d:\python\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 464, in _communicate_shutdown
    _ = self._communicate(record)
  File "d:\python\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 222, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "d:\python\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 227, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
